### ISSUE TITLE
Grid layout suggestion

### ISSUE THREAD

**Issue by joecritch** [Modernizr/modernizr-neue#30]
Hey guys,

A few people mentioned there are now less detects visible at once in Download UI's viewport. I've been considering whether we should cater for visual/passive users (i.e. someone who isn't necessarily searching, and would rather see an upfront list).

Before I PR, I've done some mockups. I'd be keen to hear what you think, and when you think this state should apply. (My thoughts are that, when searching or on a smaller screen, it should revert to the single column layout).

![grid-layout](https://cloud.githubusercontent.com/assets/24449/9882585/4cb3368c-5bcd-11e5-9fb3-cc653776a9e8.png)

**Comment by joecritch** [comment]
... another option would be to have a "List / Grid" toggle. But don't want to introduce explicit UI for no reason. And I think I prefer the idea that anyone who's not filtering using the search bar would be a passive user.

**Comment by patrickkettner** [comment]
Not a bad idea at all. Would the medium size view be two columns? Where would he metadata be at?

**Comment by patrickkettner** [comment]
-1 on the toggle

**Comment by joecritch** [comment]
Yeah we could have an intermediate 2-col layout. The metadata is still on the right-hand side, no?

**Comment by patrickkettner** [comment]
The columns could get real tight at that point. I'd be interested in seeing
the comps with the longest prop names and metadata visible

**Comment by bravokiloecho** [comment]
Strong +1 for something along these lines...

It was so much easier to know what was available and what you'd selected when you could see all the available properties at once (except the non-core).

I would have thought the buttons could shrink a little (font size and padding) to allow more to be visible at one time.

**Comment by joecritch** [comment]
@bravokiloecho Thanks. See #32 for the PR (includes slightly smaller detect buttons, too.)

**Comment by robwierzbowski** [comment]
I tweeted something about this earlier. Jumped into dev tools and tried some things out. What I found:

- Dropping the font size and line height seemed the biggest, quickest win. Because these items are part of a list group, I don't think the benefit from the amount of white space they're currently given. 
- I noted that the font sizes of multiple elements change at different viewport sizes; the options will probably need a little attention across all breakpoints to maintain an appropriate visual hierarchy. Density will help a lot, but dropping to 1 em looked a bit weird at a skinny viewport.
- I played a bit with multiple cols like @joecritch. It definitely gets more items on the page at once. But, floated alphabetical lists go against most of our natural tendencies to read :arrow_down: a column. Not saying we shouldn't, but it's something to be aware of. 
- Related: sections might help break the detects into digestible chunks.
- If we add multiple cols to the detects list, it may be a good idea to move the checkbox before the detect name. In @joecritch's mockup you can see that the checkbox is actually closer to the next column's text than its own. In the current design I felt a little pain from this as well.

**Comment by robwierzbowski** [comment]
For reference, here's the site on a 13" MacBook Pro. A pretty powerful device, and I can see about 6 options at any one time:

<img width="1280" alt="screen shot 2015-09-16 at 5 20 08 pm" src="https://cloud.githubusercontent.com/assets/925735/9918834/3a5ae7c6-5c97-11e5-807a-8e4d893c5be0.png">

**Comment by joecritch** [comment]
Thanks @robwierzbowski. Yeah my #32 also reduces font sizes. I feel your point about the checkboxes potentially being on the wrong side (this is more apparently when in a grid layout, so I'll handle this in the PR).

I'm closing this in favour of #32. If you have any suggestions beyond grid layout, let's have those as separate PRs.

**Comment by robwierzbowski** [comment]
Sounds good. I'll wait till #32 is merged then revisit.

**Comment by 1Cr18Ni9** [comment]
Does anyone can tell me is any detective property available to tell whether browser can support grid layout. Thanks in advance!
